### ISSUE TITLE
ScalaMatsuriの表記ゆれを修正

### ISSUE THREAD

**Issue by NoriakiHoriuchi** [scalajp/2018.scalamatsuri.org#106]
"Scala Matsuri" になっている

**Comment by richardimaoka** [comment]
https://github.com/scalajp/2018.scalamatsuri.org/commit/66988048ba6e2f89dc86af645dc5520abf8569c3

LGTM

**Comment by NoriakiHoriuchi** [comment]
レビューありがとうございました！
