### ISSUE TITLE
Webロゴ掲載(株式会社ヌーラボ様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#115]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=0B0APyFxCcKPJbVhiUE80VVRXNFU
リンク先:https://nulab-inc.com/ja/

**Comment by tomoco95** [comment]
#117 にてロゴ掲載完了しました
