### ISSUE TITLE
Webロゴ掲載(Paidy (株式会社エクスチェンジコーポレーション）様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#118]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=0B2L-WwulhexCZjU5U25xYjktNHc
リンク先:https://paidy.com/

**Comment by tomoco95** [comment]
#130 にて追加完了
