### ISSUE TITLE
Webロゴ掲載(株式会社サイバーエージェント様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#119]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=0BxxQP8ShbqBcY20yUk5Zd2E0bDQ
リンク先:https://adtech.cyberagent.io/

**Comment by tomoco95** [comment]
#130 にて追加完了
