### ISSUE TITLE
Web情報掲載(株式会社ヌーラボ様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#123]
---
title: "株式会社ヌーラボ"
logo: ""
plan: 
link: "https://nulab-inc.com/ja/about/careers/"
linkTitle: "Why be a Nulaber??"
---
株式会社ヌーラボは、Backlog、Cacoo、Typetalkを展開する企業です。
福岡、東京、京都、ニューヨーク、シンガポール、アムステルダムに拠点を持ち、サービスをグローバル展開させています。

▼Scalaの使用状況
・Backlog…JavaからScala/Play Frameworkに移行中のプロダクトです。
　移行についてのプレゼンテーションはこちら
　Backlogが一体いつから Scalaを遣っていないと 錯覚していた？
　http://sssslide.com/speakerdeck.com/nulabinc/scala-fukuoka-2017-backlog-is-using-scala
・Typetalk…サービス立ち上げ時からScala/Playを使ったプロダクトです。

▼Scalaを使用している募集ポジション（東京・福岡）
・Backlogチーム　サーバーサイドエンジニア
・Typetalkチーム　サーバーサイドエンジニア

▼開発環境
・Backlog
　Scala / Go / Java / JavaScript / Haxe / Kotlin / Swift / Seasar2 / Play Framework / MySQL / Git / Knockout.js / Jenkins / AWS / Mackerel / IntelliJ

・Typetalk
　Scala / Play Framework / PostgreSQL / Git / AWS / Ansible / Jenkins / Electron / AngularJS 1

▼どんな会社？
・エンジニア中心の組織
　ヌーラボにはセールス組織がありません。
　エンジニアが中心となって、プロダクト開発を行なっています。

・グローバルな環境
　ヌーラボは社員の1/4が日本語を母国語としていません。
　タスクチケットや一部のチャットは、英語で書かれています！
　（入社時に英語力のテストは一切ありません。意欲を大切にしています！）

・サービス開発は長期戦。仕事も家庭も大切に…
　子育て休暇の支給や、残業を前提としない業務設計（みなし残業なし！）など、
　長期的にサービス開発に関わるからこそ、仕事も家庭も大事にできる組織を作っています。

あなたも”ヌーラバー”になりませんか？
少しでも気になった方は、「Scala Matsuriから来た！」ことを明記の上、「応募フォーム」、又は「ヌーラバーの話を聞いてみたい」からご連絡ください！

**Comment by tomoco95** [comment]
#132 がmergeされたら閉じます

**Comment by tomoco95** [comment]
完了しました
