### ISSUE TITLE
TOPページに、はてブボタンを追加する

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2018.scalamatsuri.org#128]
せっかくプロポーザルの詳細ページに、はてブボタンを追加したので、トップページにもあると良いかも？

![_026](https://user-images.githubusercontent.com/1506707/32234771-fafb8356-bea0-11e7-8b80-3d47def7059c.png)

**Comment by grimrose** [comment]
表示されているのを確認したので、closeします。
