### ISSUE TITLE
Webロゴ差し替え(株式会社サイバーエージェント様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#138]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=0BxxQP8ShbqBcRVFROFN6U1FKdVk
リンク先:https://adtech.cyberagent.io/techblog/

**Comment by tomoco95** [comment]
ロゴ、リンク先ともに差し替えたいとのご連絡がありました。#141 にて対応中。

**Comment by tomoco95** [comment]
done
