### ISSUE TITLE
Webロゴ掲載(株式会社CyberZ様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#139]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=0B3vXoy6KddgoYWlncV9pTG9YZTA
リンク先:https://www.forceoperationx.com/

**Comment by tomoco95** [comment]
#141 にて対応中

**Comment by tomoco95** [comment]
done
