### ISSUE TITLE
Web情報掲載(株式会社CyberZ様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#140]
---
title: "株式会社CyberZ"
logo: ""
plan: 
link: "https://cyber-z.co.jp/recruit/entry/f-o-x-%E3%82%A8%E3%83%B3%E3%82%B8%E3%83%8B%E3%82%A2.html"
linkTitle: ""
---

**Comment by tomoco95** [comment]
#136 がうまくいったらこちらもやります

**Comment by tomoco95** [comment]
#204 にて完了
