### ISSUE TITLE
Webロゴ掲載(WAmazing株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#161]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=0B130_pc41DhqMFJQUVVPYVBjQ2c
リンク先:https://info.wamazing.jp/

**Comment by tomoco95** [comment]
#163 にて追加完了
