### ISSUE TITLE
Web情報掲載(WAmazing株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#164]
---
title: "WAmazing株式会社"
logo: ""
plan: 
link: "https://www.wantedly.com/companies/wamazing/projects?occupation_type=engineer"
linkTitle: ""
---
WAmazing株式会社は「日本中を楽しみ尽くす、Amazing な人生に。」のビジョンの元、外国人観光客に日本の良さを知って、さらに日本旅行を楽しんで貰う為のサービスを行っています。
現在、日本旅行中に使えるSIMカードを無料で提供し、WAmazingのアプリやWebサービスを知って貰う事で、日本旅行がさらに便利になるサービスを提供しています。

これらのサービスの裏側では Scala や Ruby を、フロントエンドとアプリでは React と ReactNative を中心にした開発を行っています。ユーザに価値を提供するために、技術を活かしてしっかりと適用していく、そんな環境での開発に興味がある方は、採用ページをご覧いただけければと思います。

**Comment by tomoco95** [comment]
#204 にて完了
