### ISSUE TITLE
「cafebabepy(JVMで動くPython処理系)の構文解析もScalaにおまかせ！」のページの項目が空のものがある

### ISSUE THREAD

**Issue by yotchang4s** [scalajp/2018.scalamatsuri.org#166]
http://2018.scalamatsuri.org/ja/candidates/YoshiakiShibutani_1/
の発表言語と聴衆の対象が空になっているのでご対応をお願いします。

**Comment by grimrose** [comment]
@yotchang4s 修正が反映されたと思いますので、確認をお願いします。

**Comment by yotchang4s** [comment]
@grimrose ありがとうございます。修正が反映されたことを確認しました。
