### ISSUE TITLE
ソーシャルボタンがない

### ISSUE THREAD

**Issue by taisukeoe** [scalajp/2018.scalamatsuri.org#21]
- [ ] Twitterのツイートボタン（カウント付き)
- [x] Facebookのシェアボタン（カウント付き)
- [x] FacebookのLikeボタン(カウント付き)
- [x] はてなブックマークボタン(カウント付き)

**Comment by grimrose** [comment]
テンプレートに各ソーシャルメディアのボタンを追加しておきます

**Comment by grimrose** [comment]
Twitterのツイート数は公式からは非提供なので、別途方法を考える必要があります

**Comment by taisukeoe** [comment]
Oops...
count.jsoonとかですかね？(使ったことないですが）
http://jsoon.digitiminimi.com/

**Comment by grimrose** [comment]
ボタンですが、横で試してみました。

<img width="807" alt="2017-10-21 21 08 32" src="https://user-images.githubusercontent.com/623724/31851606-1bba1d82-b6a4-11e7-8bc9-175580b38bc4.png">

**Comment by grimrose** [comment]
カウント付きの縦です

<img width="763" alt="2017-10-21 21 40 14" src="https://user-images.githubusercontent.com/623724/31851824-7e78019c-b6a8-11e7-92ae-62e3c32c2ed8.png">

**Comment by grimrose** [comment]
tweetのカウント付きのボタンは、後日count.jsoonの状況を見て判断します。
