### ISSUE TITLE
Webロゴ掲載(株式会社スタートトゥデイ工務店様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#223]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1KLXzTR-bLYhsbI0guKipNU46OFdzohtb
リンク先:https://www.st-komuten.jp/

**Comment by tomoco95** [comment]
#224 にて対応中

**Comment by tomoco95** [comment]
対応完了しました
