### ISSUE TITLE
Webロゴ掲載(ナイル株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#228]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1sNWrS00kCI_XGf5fvC101JQ2LQ9yQohS
リンク先:http://nyle.co.jp/

**Comment by tomoco95** [comment]
#231 にて対応中

**Comment by tomoco95** [comment]
完了しました
