### ISSUE TITLE
Webロゴ掲載(株式会社サイバーエージェント様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#233]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1xmyzF3OBll--Y3DkFPzN9BwmjNRvqEyx
リンク先:https://adtech.cyberagent.io

**Comment by tomoco95** [comment]
#234 にて対応中。
リンク先も新しく送って頂いたものに変更。

**Comment by tomoco95** [comment]
完了しました
