### ISSUE TITLE
Webロゴ掲載(株式会社ビズリーチ様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#238]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1IlGk4_OWTkRKPD6P6m2XQKhfH2u5OsUx
リンク先:http://www.bizreach.co.jp/

**Comment by tomoco95** [comment]
#239 にて対応中

**Comment by tomoco95** [comment]
完了しました
