### ISSUE TITLE
Webロゴ掲載(デザイン事務所AMIX様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#242]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1ZfOtJNnknOdAlcygzb9QXDZuFTUzHgfM
リンク先:https://amix-design.com

**Comment by tomoco95** [comment]
#247 にて対応中

**Comment by tomoco95** [comment]
完了しました
