### ISSUE TITLE
day0: Webサイトに案内用文章を掲載する

### ISSUE THREAD

**Issue by kimutansk** [scalajp/2018.scalamatsuri.org#250]
# クローズ条件

Webサイトに案内用文章を掲載されたら。

## やること

以下にあるトレーニングデーの案内用の文章をWebサイトに掲載する。

### Webサイトの案内文面
ScalaMatsuri 2018では初の試みとして、3月16日(金)にScalaMatsuri Tranining Dayを開催します。

Scalaに興味があるけど敷居が高いと感じている人に効率よく学べる場としてTranining Dayを開催することで、もっとScalaエンジニアの裾野を広げていきたいと考えています。

ScalaMatsuri Training Dayの特徴

- 基礎から、初心者がつまずきやすいところ、開発環境などScalaを始める上で必要な情報を１日で学べる
- Scalaを採用している企業の制度・風土について知ることが出来る
- Scala 入門トラック、ハンズオントラックの2トラック構成で、理論と実践が学べる
- 分散アーキテクチャやビッグデータなどScalaと関連の深い技術領域の概要や、そこでScalaを採用するメリットについて知ることができる

**Comment by tomoco95** [comment]
macのchromeで見ると「ScalaMatsuri Training Dayの特徴」がずれて見えます。
バージョンはバージョン: 62.0.3202.94（Official Build） （64 ビット）です。

safariやUbuntuのGoogleChrome、iPhoneで見るとちゃんと見えました。
[![Screenshot from Gyazo](https://gyazo.com/8eaf0e42bc02f936beb17f77dde87959/raw)](https://gyazo.com/8eaf0e42bc02f936beb17f77dde87959)

**Comment by tomoco95** [comment]
localでみると、macのchromeでちゃんと見えます。github pages側の問題でしょうか。
![2017-11-22 17 32 08](https://user-images.githubusercontent.com/19513765/33117314-52b8bb8e-cfab-11e7-86e9-cabbf692cbcd.png)

**Comment by grimrose** [comment]
会社のmacだと崩れてないですね… :think_face:

**Comment by tomoco95** [comment]
今再読込して見てみたらちゃんと配置されるようになってました。何だったのでしょう 🤔

**Comment by grimrose** [comment]
@kimutansk これcloseしちゃってもいいですよね？

**Comment by grimrose** [comment]
掲載されたので、closeします。
