### ISSUE TITLE
Webロゴ掲載(Supership株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#260]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1tPU68x0f9Oy5g6fTUxo6qFZvW9Qzqnmu
リンク先:https://supership.jp/

**Comment by tomoco95** [comment]
#261 にて対応中

**Comment by tomoco95** [comment]
完了しました
