### ISSUE TITLE
Web情報掲載(Supership株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#278]
---
title: "Supership株式会社"
logo: ""
plan: 
link: "https://recruit.supership.jp/"
linkTitle: ""
---
Supershipはデータテクノロジーカンパニーとして、「すべてが相互につながる『よりよい世界』を実現する」インターネット企業です。事業領域はWeb広告を中心にtoBからtoCにいたるまで、幅広く展開しています。

【開発環境など】
・広告事業（DSP/SSP/DMP）
Ruby、Python、Scala、Node.JS、C++、PHP、Hadoop、Spark、Hive、OpenStack

・WEBサービス（nanapi、Wakuba）
Ruby、PHP、JavaScript、AWS

・検索システム
Python、Ruby、Scala、GCP、BigQuery、ElasticSearch

・Web接客ツール
Ruby、Scala、React.JS、AWS（Aurora）、BigQuery

Supership株式会社では積極的なエンジニア採用を行っております。詳細は採用ページよりご確認ください。 みなさまのご応募をお待ちしております。

**Comment by tomoco95** [comment]
#282 にて対応中

**Comment by tomoco95** [comment]
完了しました
