### ISSUE TITLE
Webロゴ掲載(スマートニュース株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#307]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1ztJeuK1oGwvtLzV59lqWEjHWM__YLOYB
リンク先:http://about.smartnews.com/

**Comment by tomoco95** [comment]
#312 にて対応中

**Comment by tomoco95** [comment]
完了です
