### ISSUE TITLE
Webロゴ掲載(グッドフロー・テクノロジーズ 瀬良 和弘様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#308]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1xLSLOnBCcnsMcWAkC5VptGSSIG4vvdaw
リンク先:http://good-flow.com/

**Comment by tomoco95** [comment]
#312 にて対応中

**Comment by tomoco95** [comment]
完了です
