### ISSUE TITLE
Webロゴ掲載(芸者東京エンターテインメント株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#319]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1VPzjfO5e0S6fbjDJ8FPYLdf7yPqNjzB-
リンク先:https://www.geishatokyo.com/

**Comment by tomoco95** [comment]
#321 にて対応中

**Comment by tomoco95** [comment]
完了しました
