### ISSUE TITLE
Web情報掲載(芸者東京エンターテインメント株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#320]
---
title: "芸者東京エンターテインメント株式会社"
logo: ""
plan: 
link: "https://www.geishatokyo.com/#!/recruit.html"
linkTitle: ""
---

**Comment by tomoco95** [comment]
#321 にて対応中

**Comment by tomoco95** [comment]
完了しました
