### ISSUE TITLE
Web情報掲載(株式会社　セプテーニ・オリジナル様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#332]
---
title: "株式会社　セプテーニ・オリジナル"
logo: ""
plan: 
link: "http://www.septeni-original.co.jp/"
linkTitle: ""
---
### 企業概要

[セプテーニ・オリジナル](http://www.septeni-original.co.jp/)は[セプテーニ・グループ](https://www.septeni-holdings.co.jp/)における様々な開発を担当してる会社です。

高い成長を続けるソーシャルメディア（Facebook、Twitterなど）のアドテクノロジーに関するシステムや、コンシューマ向けオリジナル新作マンガの配信サービス「[GANMA！(ガンマ)](http://ganma.jp)」等を開発しており、ほぼ全てのプロダクトでScalaを採用しています。

Scala Matsuri 2016 から今回まで3回連続して将軍スポンサーです。

### 文化

コードレビューやスクラムの適用などは当然とし、ドメイン駆動設計を取り入れる等、綺麗なコードを素早くを作ることに注力しています。2017年12月現在、以下の方針の下に開発を行っています

- 我々は”高速高品質”を目指す
- 我々は保守性のあるコードを高速に生産する
- 気軽に品質を維持するため、Scalaを利用する
- プロダクトオーナーがハンドルを握るため、スクラムを採用する
- チーム全員で要求の芯を捉え続けるため、DDDを採用する
- リファクタリングをし続けるため、ユニットテストを書く
- ちゃんとやる＝遅いという思い込みを止める
- 意識を保ち続けるため、レビューを行う

詳細は[セプテーニ・オリジナル - 技術指針](http://www.septeni-original.co.jp/culture/policy.html)をご参照ください。

### 活動

Scalaを始めとした技術に関するイベントを不定期開催しています。

- [新宿Geek Lounge](https://shinjuku-geek-lounge.connpass.com/)
- [Septeni×Scala](http://septeni-scala.connpass.com/)
- [将軍達のあとの祭り](http://scala-syogun-matsuri.connpass.com/event/28124/)
- [Scala/Scrum/DDD 困ったこと50連発ガトリングトーク！！](http://scala-scrum-ddd-gatlingtalk.connpass.com/event/34172/)

### 求人

セプテーニ・オリジナルでは一緒に働ける仲間を積極的に募集しています。
Scala未経験でも構いません、ぜひご応募ください!

**Comment by tomoco95** [comment]
#340 にて対応中

**Comment by tomoco95** [comment]
完了しました
