### ISSUE TITLE
Webロゴ掲載(エムオーテックス株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#333]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1_G1cXnsgp3D_XRuKpA8ZAk5fXELZqsM9
リンク先:http://www.motex.co.jp

**Comment by tomoco95** [comment]
#338 で対応中

**Comment by tomoco95** [comment]
完了しました
