### ISSUE TITLE
Web情報掲載(株式会社VOYAGE GROUP様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#337]
---
title: "株式会社VOYAGE GROUP"
logo: ""
plan: 
link: "https://voyagegroup.com/recruit/career/jobs/engineer/"
linkTitle: ""
---

**Comment by tomoco95** [comment]
#341 にて対応中

**Comment by tomoco95** [comment]
完了しました
