### ISSUE TITLE
Webロゴ掲載(株式会社はてな様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#346]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1MwWkzU3eNvWvzxjLfzXOcVGNjtyXMuOR
リンク先:http://hatenacorp.jp/

**Comment by tomoco95** [comment]
頂いたファイルだと、2:1の比率になっていて余白が多かったのでサイズ調整をお願いしています。

**Comment by tomoco95** [comment]
画像もらいなおしました。こちらで掲載作業すすめます。
https://drive.google.com/file/d/1zRd34YE-MUjmt57yYZwk10aIQrop2G2U/view?usp=sharing

**Comment by tomoco95** [comment]
#387 にて対応中

**Comment by tomoco95** [comment]
完了しました
