### ISSUE TITLE
Webロゴ掲載(ChatWork株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#348]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=11E_cMBfyhRaQbCjYKQizJZe8QZBtkg1d
リンク先:https://go.chatwork.com/ja/

**Comment by tomoco95** [comment]
リンク先が抜けちゃってるので確認します

**Comment by tomoco95** [comment]
リンク先の確認が取れましたので、ロゴ掲載します。
#827 にて対応中です。

**Comment by tomoco95** [comment]
完了しました
