### ISSUE TITLE
Webロゴ掲載(パーソルキャリア eiicon様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#352]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1RDSm-_vLZhp-61Dgfv0NYVHfN90Cd8Ta
リンク先:https://eiicon.net/

**Comment by tomoco95** [comment]
#356 にて対応中

**Comment by tomoco95** [comment]
完了しました
