### ISSUE TITLE
Web情報掲載(株式会社サイバーエージェント様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#355]
---
title: "株式会社サイバーエージェント"
logo: ""
plan: 
link: "https://www.cyberagent.co.jp/careers/professional/jobs3/contents_type=1043"
linkTitle: ""
---
恐れ入ります、以下のリンクに掲載内容をまとめておりますので、フォントサイズ、リンク先の設定等、このような形でお願いできますでしょうか？

https://drive.google.com/open?id=1UmVW5PDOb2UxsWndBpAqvQ-d60k6gqmS_4eZv2b4qOY

**Comment by tomoco95** [comment]
#361 にて対応中です

**Comment by tomoco95** [comment]
完了しました
