### ISSUE TITLE
Web情報掲載(株式会社エフ・コード様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#391]
---
title: "株式会社エフ・コード"
logo: ""
plan: 
link: "https://f-code.co.jp/recruit/engineer.html"
linkTitle: "応募する"
---
・企業概要
エフ・コードはSaaS 事業と Web コンサルティング事業を展開する会社です。創業時より展開する Web コンサルティング事業の知見に基づき、マーケティングソフトウェア「f-tra（エフトラ）」を日本・タイ・香港・インドネシアの 4 拠点で提供しています。現在技術基盤の大幅な強化を図っており、Scalaを用いた新規プロダクトを鋭意開発中です。
ScalaMatsuri 2017では、旗本スポンサーとしてご協力しました。

・技術・組織についての考え方
Scalaをベースとする技術基盤により、プロダクト・技術両面の非連続成長を目指しています。技術の複雑さを楽しめるシンプルで強靭な組織を構築するため、環境の充実・正当な評価・円滑なコミュニケーションなどに留意して仕組みを作っています。

またScalaMatsuriへのスポンサードをはじめ、一企業の立場から技術コミュニティを積極的に支援しています。個人の成長と会社の成長が健全に作用し合う組織づくりのため、優秀な顧問陣を招聘しており、Scalaに関することはもちろんチームビルディングに至るまで、あらゆる相談が可能な環境です。

・求人
エフ・コードではScalaで開発を行う仲間を大募集しています！ ぜひご応募ください！

**Comment by tomoco95** [comment]
#394 で対応中

**Comment by tomoco95** [comment]
完了しました
