### ISSUE TITLE
Webロゴ掲載(株式会社アットウェア様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#447]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1aWACJk8ILsHmKCmgj7i1WPDIoM0uuQfC
リンク先:https://www.atware.co.jp/

**Comment by tomoco95** [comment]
#448 にて対応中

**Comment by tomoco95** [comment]
完了しました
