### ISSUE TITLE
tamas puskiさんに応募枠の確認をする

### ISSUE THREAD

**Issue by Keita-N** [scalajp/2018.scalamatsuri.org#463]
ref: #404 

10分枠で応募しているが、45分話してみたい旨が記載されていたので確認した方がいいかも。
確認取れなければ、記載のまま10分枠でよい。

**Comment by Keita-N** [comment]
https://github.com/scalajp/2018.scalamatsuri.org/pull/404/commits/921ae015caa346ad65f5456faa2f5d10162aa4c4#diff-963078530570e11368caef3963c96874L25

**Comment by taisukeoe** [comment]
10分枠で確定しましょう。
