### ISSUE TITLE
Web情報掲載(株式会社はてな様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#470]
---
title: "株式会社はてな"
logo: ""
plan: 
link: "http://hatenacorp.jp"
linkTitle: ""
---
はてなは「『知る』『つながる』『表現する』で新しい体験を提供し、人の生活を豊かにする」をミッションに、「[はてなブックマーク](http://b.hatena.ne.jp/)」「[はてなブログ](http://hatenablog.com/)」などのソーシャルサービスを展開してきました。最近はこれまでのサービス開発・運用知見を活かし、サーバー監視ツール「[Mackerel](https://mackerel.io/ja/)」などビジネス向けの製品や、受託サービスの開発・運用も行っています。
Scala は Mackerel やはてなブログ、はてなブックマークで採用され、稼働しています（[はてなにおけるマイクロサービスとScala](https://speakerdeck.com/aereal/microservices-and-scala-at-hatena)、[はてなブックマーク in Scala](http://www.slideshare.net/oarat/2015-0801-scala)、[Mackerel における Scala/Play](http://2014.scalamatsuri.org/ja/program/index.html#session-b-5)）。
技術で人の生活を豊かにすることに情熱を持てる方、ぜひはてなで働いてみませんか？ 勤務地は京都と東京から選択できます。詳しくは採用ページや開発者ブログをご覧ください。

[採用情報 - 株式会社はてな](http://hatenacorp.jp/recruit/)
[Hatena Developer Blog](http://developer.hatenastaff.com/)

**Comment by tomoco95** [comment]
#470 にて対応中

**Comment by tomoco95** [comment]
完了しました
