### ISSUE TITLE
Webロゴ掲載(TIS株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#472]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1-6DPWy0zueUfMxxQuoDVcu9kiq1Kd9eP, https://drive.google.com/open?id=1PcHhlgKNlTiYjTzY40z8OJN-LnFqwh1-
リンク先:https://www.tis.jp/service_solution/goreactive/

**Comment by tomoco95** [comment]
#501 にて対応中

**Comment by tomoco95** [comment]
完了しました
