### ISSUE TITLE
http://2018.scalamatsuri.org/en/candidates/JacekKunicki_1 のアイコンが見えない

### ISSUE THREAD

**Issue by grimrose** [scalajp/2018.scalamatsuri.org#497]
iconに指定されていたurlが404で返ってくる

**Comment by rucek** [comment]
Hi, actually it's my photo whose URL is broken, here's a working one: 

https://dl.dropboxusercontent.com/content_link/k7ufG6PshkhaPyQYAAIPUjUHa1hjUpHVKhFhJkIMXz3ssctCkcGOpB6GhHEq311k/file

Shall I submit a PR or will you fix it yourselves?

**Comment by grimrose** [comment]
@rucek Thank you.

So. I see your url is private.

Could you drag and drop the photo here?

I try to make PR.

**Comment by rucek** [comment]
Hmm, seems that the dropbox links are temporary. I'm attaching the photo here, sorry for the confusion. Thanks in advance for sorting this out.

![201612-0505](https://user-images.githubusercontent.com/271900/34161445-f52af9d8-e4d0-11e7-9ac2-3c12004badaf.jpg)

**Comment by grimrose** [comment]
@rucek thanks! 

Just a moment, please. I make PR soon.

**Comment by grimrose** [comment]
@rucek Sorry. I made you wait. please check your proposals.

http://2018.scalamatsuri.org/ja/candidates/JacekKunicki_1/

http://2018.scalamatsuri.org/en/candidates/JacekKunicki_1/

**Comment by rucek** [comment]
@grimrose looks good, thank you for the quick fix!
