### ISSUE TITLE
和訳: Martin Thompsonさんによる「Functional Performance」

### ISSUE THREAD

**Issue by Keita-N** [scalajp/2018.scalamatsuri.org#64]
ref: #62

**Comment by ttmsk** [comment]
@Keita-N 
ざっくり翻訳で、レビューまたは参考にしてください。
気になるところは、（）書きにして明記しておきます。

name: Martin Thompson
title: “関数型プログラミングによるパフォーマンス"
length: 40
audience: Intermediate: 仕様に精通していなく、原則に馴染みがある人向け
language: English
twitter: mjpt777
github: mjpt777
icon: https://real-logic.co.uk/martin-thompson.png
organization: Real Logic
tags:
- Functional Programming
- Best Practices
- Software Design and Architecture
suggestions:+ -　関数型プログラミングとアプリケーションのパフォーマンスに関しての真実と噂話を区別したい人々（ want to separate the hype from reality　をどのように訳にしてよいのか）

関数型プログラミングがマルチコアの問題をどのように解決するのかを聞いた事があると思います。
今なお、関数型プログラミングでのパフォーマンスの問題がどのように起こるかについても聞いた事があるでしょう。
もしそうでなければ、ここ10年間どこに隠れていたのですか？事実を別の事実とどのように区別しますか？（If not , then where have you been hiding that last 10 years? How do we separate the facts from the alternative facts?　<- この冗談混じりの文章の訳）
この講演では、関数型プログラミングが優れたパフォーマンスを提供し、マルチコアの要求を満たすことができるかどうかの問題を解決するために、現在のプラットフォームの内部動作についての話をします。

この講演では、ソフトウェアパフォーマンスを管理する最も関連性の高い法律について説明し、最も要求の厳しい金融分野に対応するための実装を行った証拠をもとに、パフォーマンスに関する真実についての話をします。（put them into context with evidence 　<- この表現と締めの言葉をどのようにするのか）

**Comment by richardimaoka** [comment]
> want to separate the hype from reality
> @richard 誇張と現実を分けて考えたい人

hypeは[誇張とか誇大広告とかそういう意味](https://eow.alc.co.jp/search?q=hype)ですね。

「関数型原理主義者」あるいは「よくわかってないのに関数型すげー、それを宣伝するオレCOOL」みたいな人々は関数型のいいところばっかり言って、悪いところや難しいところは言わないので、そんなデマと現実を分けましょう、ということかと思います。

> If not , then where have you been hiding that last 10 years? 
> @ttmsk   もしそうでなければ、ここ10年間隠れてきたのはどこですか？
> @richard もし過去10年間でこういった話を聞いたことがなかったら、おそらくどこかに隠れていた人じゃないかと思います。

かなり意訳ですがwhere have you been hiding last 10 years -> 「ここ10年間隠れてきたのはどこですか？」と直訳してしまうと、原文の冗談めかしたニュアンスよりちょっと攻撃的に聞こえてしまう気がするのでこうしてみました。

> How do we separate the facts from the alternative facts?
> @richard どうやって(某国の大統領が言うところの)「オルタナティブ・ファクト」つまり嘘や誇張から事実を見抜くことができるのでしょう？

[alternative factsはこれ](https://eow.alc.co.jp/search?q=alternative+facts&ref=sa)ですね。日本人には通じない冗談だと思うので、ちょっと踏み込んだ訳にしました。

**Comment by richardimaoka** [comment]
あ、最後の見逃してました。

> put them into context with evidence taken from building implementations to serve the most demanding financial domains.
> @richard 最も要求水準の高いセクタである金融業界での開発・実装で得た経験とにもとづいて説明していきます。

put them into contextは「○○の文脈で話をする」みたいな意味ですが、私は無理に「文脈」という言葉を訳に入れようとしたらうまく行かなかったので↑のようにしてしまいました。あとevidenceは普通は「証拠」という意味ですが、多分この文だと「経験」くらいのもっとゆるいニュアンス。
