### ISSUE TITLE
英訳: 奥田 佳享 さんによる「squbs、イイよ」

### ISSUE THREAD

**Issue by Keita-N** [scalajp/2018.scalamatsuri.org#79]
ref: #73

**Comment by yohei1126** [comment]
原文の「豊富なツールセットを持ちますが、プロダクションレベルで運用するには、ログやモニタリング、アプリケーションライフサイクルなど品質特性にも目を配る必要があります。」がいまいち意味が分かりません。直訳すると意味が通じなさそうです。

* プロダクションレベルで運用するには、Akka の品質特性にも目を配る必要がある。
* そのためには、ロギング、モニタリング、アプリケーションライフサイクル管理などを行う必要がある。
* Akka のツールセットには上記が含まれていない。
* そのため、加えて squbs を使った方が良い。

という流れでしょうか？

**Comment by yohei1126** [comment]
私の解釈ベースで、翻訳を書いてみました。

```
In order to use Akka in production, we also need to pay attention to quality
characteristics using logging, monitoring and application life cycle management.
Although Akka has a rich tool, it does not cover the area.
In this session, I will introduce a library called squbs developed by PayPal in order to
achieve this.
squbs's design principal and tools are completely different from all-in-one frameworks. 
Unfortunately they do not have enough information in Japanese. So, it would be happy
for me if this session cloud provide useful information to you.
(By the way, I am not a contributor. I just want to let you know my favorite tool ;-D)
```

**Comment by richardimaoka** [comment]
これは多分「品質特性」という単語の選択が悪いですね。むしろこの単語を抜けばスッキリ意味が通る。

* プロダクションレベルで運用するには、ロギング、モニタリング、アプリケーションライフサイクルに目を配る必要がある

* Akka のツールセット単体では上記をプロダクションレベルで運用できない（ログ機構はあるがfluentdみたいにアグリゲートしない、モニタリングは可視化ツールのようなものはない、アプリケーションライフサイクル管理は含まれていないというわけではないが注意を要する）
* そのためsqubsを使ったほうが良い
そのため、加えて squbs を使った方が良い。

**Comment by yohei1126** [comment]
ありがとうございます。更新しました。

**Comment by yoskhdia** [comment]
はい、そちらの解釈で充足しています。
なお、「品質特性」はNonfunctional requirementに関連するものとして使用していました。
https://www.ogis-ri.co.jp/otc/hiroba/technical/JavaPress_ISO9126/
