### ISSUE TITLE
Webロゴ掲載(Lightbend, Inc様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#797]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=14lF4A34STY3Qm1K8WKvL6NIgxwH-_0xg
リンク先:https://developer.lightbend.com/

**Comment by tomoco95** [comment]
20*7のロゴをいただきました。こちらを掲載します。
https://drive.google.com/drive/folders/1OotWw9KVI2UnpXrRmvo5AxaQbu3u1w0O?usp=sharing

**Comment by tomoco95** [comment]
#820 にて対応中

**Comment by tomoco95** [comment]
完了しました
