### ISSUE TITLE
スポンサー募集ページPDF資料の差し替え

### ISSUE THREAD

**Issue by tomoco95** [scalajp/2018.scalamatsuri.org#799]
[スポンサー募集ページのPDF資料](http://2018.scalamatsuri.org/ja/sponsors/sponsorship.pdf)を下記へ差し替えます。
https://drive.google.com/file/d/19PCIEbY7RhB7yJG_0DqIPmf5gCuXP6Hn/view?usp=sharing

変更箇所
- スポンサーさまに準備して頂くノベルティ個数の確定
day0 => 200個
day1-day2 => 700個
- トレーニングデー（仮）=>Tranining Dayにアップデート

**Comment by grimrose** [comment]
@tomoco95 更新したので、確認をお願いします。

**Comment by tomoco95** [comment]
@grimrose 確認しました、ばっちりです。対応ありがとうございました。
