### ISSUE TITLE
Webロゴ掲載(イタンジ株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#832]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1bJ-FgnPaj9B9zjyW9CCtTiPTL7Raqe4T
リンク先:https://www.itandi.co.jp/

**Comment by tomoco95** [comment]
#833 にて対応中

**Comment by tomoco95** [comment]
完了しました
