### ISSUE TITLE
Webロゴ掲載(SUGAR株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#834]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1HidSQn3Mh6DCW6LxX8kLLlmXN9RiUtqk
リンク先:http://sugarcorp.jp/

**Comment by tomoco95** [comment]
#835 にて対応中

**Comment by tomoco95** [comment]
対応完了しました
