### ISSUE TITLE
Webロゴ掲載(日本インサイトテクノロジー株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#840]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1jg609I4bglc7vQNJ7bTg1ng1CURB_BUg
リンク先:http://www.insightech.co.jp/

**Comment by tomoco95** [comment]
#842 にて対応中。

**Comment by tomoco95** [comment]
完了しました
