### ISSUE TITLE
Webロゴ掲載(株式会社クラウドワークス様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#850]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1fmujRE6PiM938gAU7tkr3wnsRsgqgQcM
リンク先:https://crowdworks.co.jp/

**Comment by tomoco95** [comment]
#853 にて対応中

**Comment by tomoco95** [comment]
完了しました
