### ISSUE TITLE
Webロゴ掲載(キャッシュビー株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#874]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1HwPj1JGTsOtY7wWihNAHHtZSQtiKKYoT
リンク先:https://cashb.jp/

**Comment by tomoco95** [comment]
#875 にて対応中

**Comment by tomoco95** [comment]
完了しました
