### ISSUE TITLE
Web情報掲載(キャッシュビー株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#876]
---
title: "キャッシュビー株式会社"
logo: ""
plan: 
link: "https://cashb.jp/"
linkTitle: "CASHbについてはこちらでもご覧いただけます"
---
### 企業概要

キャッシュビー株式会社は、毎日のお買物に役立つ節約アプリCASHbを運営しています。高いキャッシュバック率と貯まったポイントを現金化できることを強みとしており、企業様にはアプリから店頭送客を実現できるダイレクトマーケティングツールとして、ユーザー様には気軽に節約できるアプリとしてご活用いただいています。

CASHbの開発には、サーバーサイドに Akka HTTP, クライアントサイド (iOS, Androidアプリ) に Scala.JS など、ほぼ全面的に Scala を採用しています。

企業Webサイト: [http://www.cashb.co.jp/ja/](http://www.cashb.co.jp/ja/)

### サービス概要

節約アプリ『CASHb』は、これまでになかった新しいキャッシュバックサービスです。アプリ内で広告や動画閲覧・アンケート回答をしてから商品を購入すると、現金化可能な「CB」が貯まります。そのCBを現金や電子マネーなどで受け取ることができます！

キャッシュバック先は、銀行口座や電子マネー (楽天Edy / Amazonギフトカード / iTunesギフトカード / nanaco / V−プリカ / WAONポイントなど) など多彩です。気軽に、でもしっかり節約したい！という方はぜひお試しください！

**Comment by tomoco95** [comment]
#878 にて対応中

**Comment by tomoco95** [comment]
完了しました
