### ISSUE TITLE
Webロゴ掲載(株式会社FOLIO様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#877]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1XLlrbbhPBoFj9oZlNxrQJQzCXA71eSh3
リンク先:https://folio-sec.com/

**Comment by tomoco95** [comment]
#879 にて対応中

**Comment by tomoco95** [comment]
完了しました
