### ISSUE TITLE
Webロゴ掲載(LOGOLO様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#885]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=15XwW8XTIQdahzG9XxeHO03O7dgahZOLk
リンク先:https://lo-go-lo.com

**Comment by tomoco95** [comment]
#887 にて対応中

**Comment by tomoco95** [comment]
完了しました
