### ISSUE TITLE
Webロゴ掲載(ASOBO DESIGN様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#886]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1pZN1hBySggf_0qPAqN0cDsySBssNFTQN
リンク先:https://asobo-design.com/nex/

**Comment by tomoco95** [comment]
#887 にて対応中

**Comment by tomoco95** [comment]
完了しました
