### ISSUE TITLE
Webロゴ掲載(レバレジーズ株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#890]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1OOz57Ma4tB8F6Su7FIN-L4bNx7bXTs9V
リンク先:https://career.levtech.jp/

**Comment by tomoco95** [comment]
#891 にて対応中

**Comment by tomoco95** [comment]
完了しました
