### ISSUE TITLE
スポンサー募集ページのclose

### ISSUE THREAD

**Issue by tomoco95** [scalajp/2018.scalamatsuri.org#900]
スポンサー募集が3/2(金)までです。
3/3になったら、webサイトの[スポンサー募集ページ](http://2018.scalamatsuri.org/ja/sponsors/)とヘッダーの「スポンサー募集」の文字を隠したいです。

英語・中国語はスポンサー募集ページがないので、日本語ページのみの対応で大丈夫です。

**Comment by grimrose** [comment]
募集のページのcloseを確認したのでcloseします。
