### ISSUE TITLE
Web情報掲載(TIS株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#920]
---
title: "TIS株式会社"
logo: ""
plan: 
link: "https://www.tis-careers.com/job.phtml?job_code=447"
linkTitle: "応募する"
---
# 企業概要
TISは、SI・受託開発に加え、データセンターやクラウドなどサービス型のITソリューションを多数提供。同時に、中国・ASEAN地域を中心としたグローバルサポート体制も整え、金融、製造、流通/サービス、公共、通信など様々な業界で3000社以上のビジネスパートナーとして、お客様の事業の成長に貢献しています。新技術の研究開発にも積極的に取り組み、リアクティブシステムのリーディングカンパニーであるLightbendの国内初の認定コンサルティングパートナーとして、Akka／Play／Scalaなどを利用したリアクティブシステムの構築をサポートするコンサルティングサービスを提供しています。

詳しくは「[弊社キャリア採用サイト](https://www.tis.co.jp/career/)」を御覧ください。

# ScalaやAkkaを使った研究開発
新しい技術を開拓し、TISのビジネスに活かすための研究開発を行うエンジニアを求めています。社会的インパクトの大きいエンタープライズシステムに関わり、あなたの高い技術力で豊かな未来に貢献できるのは大規模SIerでありながら新しい技術へチャレンジを続けるTISならではです。

詳しくは弊社キャリア採用サイトの「[募集職種：オープンシステムで高可用性を実現する技術の研究開発](https://www.tis-careers.com/job.phtml?job_code=447)」を御覧ください。

# ともに働く人、募集中
TISで一緒に働ける仲間を募集しています。われわれは自社のビジネスに活かすR&D活動だけでなく、技術イベントの開催、ScalaMatsuriなどのイベントでの登壇、[Akka実践バイブル](https://www.shoeisha.co.jp/book/campaign/akka/)などの執筆活動も積極的に行っています。

下記よりご応募お待ちしております。ScalaMatsuriでTIS前出までお声がけいただいても結構です（3/18（日）の[Akka実践バイブルワークショップ](http://2018.scalamatsuri.org/ja/candidates/YugoMaede_1/)で登壇予定）。

**Comment by tomoco95** [comment]
#921 にて対応中

**Comment by tomoco95** [comment]
完了しました
