### ISSUE TITLE
Webロゴ掲載(株式会社オンデオマ様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#922]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1h4-ojasL9HOcqFoYL7pxvz2W3aANflM4
リンク先:https://www.ondeoma.com/

**Comment by tomoco95** [comment]
#923 にて対応中

**Comment by tomoco95** [comment]
完了です
