### ISSUE TITLE
Webロゴ掲載(スフィアリンクス株式会社様)

### ISSUE THREAD

**Issue by matsuri-ops** [scalajp/2018.scalamatsuri.org#929]
- [x] リポジトリにロゴを入れる
- [x]  ymlファイルを変更する

ロゴ画像:https://drive.google.com/open?id=1AocIcVTJoRQX0YT_hAouXGo12sLOQBDG
リンク先:http://spherelinks.co.jp/

**Comment by tomoco95** [comment]
#935 にて対応中

**Comment by tomoco95** [comment]
完了しました
